name: CI-solicitacao-tryout-front-mfs

on:
  push:
    branches:
      - main
jobs:
  checkout-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Protocol SCP server remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ". , !node_modules"
          target: "projetos/Mfs/solicitacao-tryout/front"
      - name: Deploy to Sever
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: cd /home/app/projetos/Mfs/solicitacao-tryout/ && docker-compose down && docker-compose up -d --build
